name: 'Setup Kit CLI'
description:
  'Setup the Kit CLI on your runner. The Kit CLI is a CLI tool for managing AI
  models.'
author: 'kitops.ml'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'terminal'
  color: 'green'

# Define your inputs here.
inputs:
  version:
    description: 'The version of Kit CLI to install. Defaults to `latest`.'
    default: 'latest'
    required: false
  token:
    description: |
      Used to pull kit CLI releases. Since there's a default, this is typically not needed to be suplied.
      When running this action on github.com, the default value is sufficient.
      When running on GHES, you can pass a personal access token
      for github.com to avoid rate limiting.
    default:
      ${{ github.server_url == 'https://github.com' && github.token || '' }}

# Define your outputs here.
outputs:
  kit-path:
    description: 'The path to the installed Kit CLI.'

runs:
  using: node20
  main: dist/index.js
